# fly.toml - Configuration for deploying to Fly.io

app = "workflowgenie-mcp"
primary_region = "iad" # Washington DC - choose a region closest to your users

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[env]
  PORT = "3000"
  NODE_ENV = "production"
  LOG_LEVEL = "info"
  ENABLE_REQUEST_LOGGING = "true"

# Note: Sensitive environment variables should be set using 
# fly secrets set KEY=VALUE
# Examples:
# fly secrets set CEQUENCE_API_KEY=your_api_key_here
# fly secrets set DESCOPE_PROJECT_ID=your_project_id_here
